### ISSUE TITLE
Reaktion auf Geschäfts und Privatkunden (Marktgeschehen)

### ISSUE THREAD

**Issue by Ermodo** [Stonks2Moon/Simulation#1]

**Comment by Ermodo** [comment]
Nicht auf einzelne Kunden, sondern auf markgeschehen

**Comment by jangruebener** [comment]
@Patrickmischka lass uns hier bitte am Donnerstag nochmal zusammen aus der fachlich Perspektive drüber schauen, ob wir das mit unserem bisherigen Konzept schon ausreichend berücksichtigen oder hier bei einer Implementierung noch TODOs und Aufwände auf uns zukommen.

**Comment by Michi0400** [comment]
Die Reaktion auf andere Marktteilnehmer wird nicht explizit in der Simulation abgebildet. Durch die verschiedenen Szenarien (hohes Volumen, niedriges Volumen, etc.) haben die Marktteilnehmer in jedem Szenario durch ihre Orders eine unterschiedliche Wirkung auf den Markt. Diese Auswirkung wird als Reaktion auf Geschäftskunden und Privatkunden gesehen.
