### ISSUE TITLE
Vorstellung Prototyp 

### ISSUE THREAD

**Issue by jangruebener** [Stonks2Moon/Simulation#13]

**Comment by jangruebener** [comment]
- Frontend: @Patrickmischka @jangruebener 3 Minuten
- Vorstellung Szenarios: @Michi0400 @Patrickmischka  5 Minuten
- Realisierung der Szenarios: @Ermodo 3 Minuten
- Geschäftsprozessanalyse / -modelierung @troykessler 3 Minuten
- Schnittstellendokumentation @aaronschweig 3 Minuten
- Vorstellung der Arbeitsweise @jangruebener  2 Minuten

**Comment by Patrickmischka** [comment]
Unter Umständen sind zugrundeliegende Daten schlecht und müssen nochmal genauer nachgeschaut und ggf. angepasst werden.
