### ISSUE TITLE
Eventkommunikation

### ISSUE THREAD

**Issue by Ermodo** [Stonks2Moon/Simulation#2]

**Comment by aaronschweig** [comment]
@Ermodo das klingt interessant, was ist damit gemeint? 😉

**Comment by Ermodo** [comment]
@aaronschweig das stand auf den anforderungsfolien. Ich meine das wäre das gewesen, dass Börseninfos, als aud den Privat/geschäftsanwendungen in die simulation einbezogen werden

**Comment by troykessler** [comment]
Börsennachrichten können nun mit dem news service oder mit der news api in einen Telegrammchannel gesendet werden. Testabdeckung liegt bei 100%.
