### ISSUE TITLE
Bestimmung von fünf Tagesszenarien

### ISSUE THREAD

**Issue by Patrickmischka** [Stonks2Moon/Simulation#20]
* Festlegung von fünf relevanten Markttagen, welche auf unterschiedliche Marktsituationen hinführen.
* Detaillierte Tagesdaten in Minutenformat
* tbd

**Comment by Michi0400** [comment]
SAP-Aktie als Referenz
26.10.2020 --> Kursabsturz durch Übernahme 
01.10.2020 --> geringes gehandeltes Volumen
19.06.2020 --> hohes gehandeltes Volumen
24.04.2019 --> positive Nachricht
22.10.2019 --> normaler Handelstag mit durchschnittlichen Volumen

**Comment by Patrickmischka** [comment]
Dazugehörige CSV-Dateien: [Verschiedene Tagesszenarien.zip](https://github.com/Stonks2Moon/Simulation/files/6042997/Verschiedene.Tagesszenarien.zip)

**Comment by Michi0400** [comment]
Umgewandelt in JSON-Dateien
[VerschiedeneTagesszenarienJSON.zip](https://github.com/Stonks2Moon/Simulation/files/6043091/VerschiedeneTagesszenarienJSON.zip)
