### ISSUE TITLE
Orders erstellen

### ISSUE THREAD

**Issue by Ermodo** [Stonks2Moon/Simulation#21]
Anbindung an Börse, sodass Orders erstellt werden können

**Comment by aaronschweig** [comment]
#5

**Comment by aaronschweig** [comment]
Zuerst wird ein MockStockMarket implementiert, bis die "reale" Börse angebunden werden kann.

**Comment by jangruebener** [comment]
Im Code werden bereits Orders erstellt. Anbindung zur Börse fehlt und ist hier Stopping Point!
