### ISSUE TITLE
relevante Dokumente für Projekt identifizieren

### ISSUE THREAD

**Issue by jangruebener** [Stonks2Moon/Simulation#39]

**Comment by jangruebener** [comment]
- SMART Ziele

**Comment by Patrickmischka** [comment]
Unter Umständen relevante Projektmanagementdokumente:

- [ ] Lösungsfindung ✔️
1. Grundsätzlicher Entwurf
2. Wege zur Umsetzung
3. Finales Vorgehen zur Umsetzung
- [ ] Themenbewertung ❌
- [ ] Stakeholderanalyse ❌
- [ ] Nutzenanalyse ❌
- [ ] Pflichtenheft, Lastenheft, Wunschliste ❌
- [ ] Projektdefinition ❓
- Formalia
- Inhaltlich
- [ ] SMART: Zielkriterien ❌
- [ ] Risikomanagement ❌
- Risikomatrix
- Risikoinventar
- [ ] Work Breakdown Structure ✔️
- [ ] Projektorganisation ✔️
- [ ] Projektstrukturplan ✔️
- [ ] Ressourcenplan ❌
- [ ] Netzplan ❌
- [ ] Projektdokumentation ✔️
- [ ] Projektstatusbericht ✔️

**Comment by jangruebener** [comment]
Die mit einem Hacken versehenen Dokumente wollen wir umsetzen und der Abgabe hinzufügen. Kreuze werden nicht bearbeitet. Fragezeichen sind noch zu klären

**Comment by jangruebener** [comment]
N.A. da kein Teil der Anforderungen!
