### ISSUE TITLE
Micro-Frontend Marktanalysen

### ISSUE THREAD

**Issue by Ermodo** [Stonks2Moon/Simulation#4]

**Comment by jangruebener** [comment]
First Draft UX-Simulation & Auswahl von Szenarien:

![UX Simulation](https://user-images.githubusercontent.com/43882912/109299595-a44c5d80-7835-11eb-8e62-9a56ce50fc52.png)


Farbcodes:

Blau: 14, 32, 74; Hex: #0E204A
Orange: 255, 125, 0; Hex: #FF7D00
Grau: 91, 91, 91; Hex: #5B5B5B
Weiß: 0, 0, 0; HEX: #FFFFFF
