### ISSUE TITLE
Schnittstellen definieren

### ISSUE THREAD

**Issue by Ermodo** [Stonks2Moon/Simulation#5]
Mit den anderen Gruppen sich abstimmen, wer welche Schnittstellen anbietet

**Comment by aaronschweig** [comment]
@Ermodo @troykessler @jangruebener habt ihr in den nächsten Tagen kurz Zeit? Würde gerne mit euch mal die internen Anforderungen besprechen und schonmal ein Interface für den Core-Service erarbeiten, damit wir evtl. schon weiter in der entwicklung sein können, ohne auf andere warten zu müssen.

**Comment by Ermodo** [comment]
@aaronschweig @troykessler schreibt mir einfach auf dc wenn ihr zeit habt

**Comment by jangruebener** [comment]
@aaronschweig  Ich würde mich auch aus fachlicher Sicht einbringen. Fände das super wenn ich bas nächste schon als unsere Vorstellung an die anderen herantragen und ihnen vorstellen kann 👍🏻 Bin zeitlich flexibel

**Comment by aaronschweig** [comment]
Ich kann das Thema angehen, sobald es neue Fortschritte im https://github.com/Stonks2Moon/Boerse gibt. Die Gruppe hat mir mitgeteilt, dass das voraussichtlich im Rahmen der nächsten Vorlesung sein wird 😄

**Comment by jangruebener** [comment]
aktueller Stand:

https://github.com/Stonks2Moon/Simulation/blob/feature/frontend-integration/backend/src/scenarios/README.md
